### ISSUE TITLE
Map new carticle ids to old ones (or plan migration)

### ISSUE THREAD

**Issue by jmelot** [georgetown-cset/article-linking#24]
Includes soliciting people's opinions on what is least painful to do here

**Comment by jamesdunham** [comment]
The case I'm most worried about is a user combining v2 and v3 IDs unwittingly in analysis. There are a lot of merged_ids out there in personal/project datasets and in Sheets. I think our priority should be to prevent analytic mistakes.

It'd be easy for a user to join v2 and v3 IDs, then have some pubs silently dropped while other pubs fundamentally change from their perspective: the titles and abstracts they've manually reviewed, now different; the FoS or AI relevance they've selected on, changed. 

Maybe the place to start here is: what's our recommendation for analysts? How we handle IDs would ideally be aligned. I expect it'll be to re-run all analysis on the new merged corpus. If so we could ensure compliance / avoid an analytic foot-gun by assigning entirely new merged_ids. 

There might then be cases where parts of an old analysis (e.g. manual labels in a Sheet) need to be migrated from v2 to v3 merged_ids. We could provide a FAAQ + data for that.
