### ISSUE TITLE
Consider using mag ids as a crosswalk

### ISSUE THREAD

**Issue by jmelot** [georgetown-cset/article-linking#29]
S2, Lens, and OA have mag ids. On one hand, we could obviously use these to link articles together. On the other hand, this is a linking method that only applies through the end of the time period MAG was around. I think I'm inclined to just ignore the mag ids for consistency but should chat with others about it

**Comment by jamesdunham** [comment]
Ignoring the MAG IDs would discard a great deal of information—they’re available for 80-90% of the years we might include in typical analysis, more in MOS. But OA has incorporated all of that data and is hopefully doing no worse at linkage than MAG—and better over time. So I’m inclined to agree.
